config/routes.rb
BvtApp::Application.routes.draw do
  get "users/new"

  match '/contact', :to =>'pages#contact'
  match '/signup', :to => 'users#new'
  
  get "pages/home"

  get "pages/contact"

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Create a new user"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    base_title = "Build Verification Test Application"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer> 
	<nav class="round">
		<ul> 
			<li><%= link_to "Contact", contact_path %></li> 
		</ul> 
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= image_tag("logo.png", :alt => "Sample App", :class => "round") %> 
	<nav class="round">
<ul> 
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Sign In", "#" %></li>
</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]> 
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> 
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> 
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
	<%= render 'layouts/stylesheets'%>
  	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "jquery.rails.js" %>
  	<%= csrf_meta_tag %>
</head>
<body>

	<div class="container"> 
		<%= render 'layouts/header' %>
		<section class="round">
			<%= yield %> 
		</section>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Contact Mike Malloy (mmalloy@zynga.com) with any questions</p>

app/views/pages/home.html.erb
<h1>BVT Application</h1>
<p>This is the home page for the BVT Application</p>

<%= link_to "Create new user", signup_path, :class => "signup_button_round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>